image: php:7.3

pipelines:
  default:
    - step:
        name: Build
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
        artifacts:
          - vendor/**
    - parallel:
        - step:
            name: Code Mess Detector
            script:
              - php ./vendor/bin/phpstan analyze -l 6 ./src ./config
        - step:
            name: Code Sniffing
            script:
              - php ./vendor/bin/phpcs
        - step:
            name: Unit Tests
            script:
              - php ./vendor/bin/phpunit --testsuite=Unit
        - step:
            name: Integration Tests
            script:
              - php ./vendor/bin/phpunit --testsuite=Integration
